### PR TITLE
Add symbolic names to dir() function result IMap keys

### PR DESCRIPTION
**Pull request by fvacek**

### CODE REVIEW

**Comment by Cynerd** [comment]
Please use the same formatting as is already used in history (`1` (*name*)).

**Review by Cynerd — CHANGES_REQUESTED** [review]
Please use the same formatting as is already used in history (`1` (*name*)).

**Comment by fvacek** [comment]
> Please use the same formatting as is already used in history (`1` (_name_)).

Parentheses are used for bit shift already in case of `flags` field, so we will get something like:
2 (*IsGetter*) (`1 << 1`): specifies that method is a getter ... 

2 `IsGetter` (`1 << 1`): specifies that method is a getter ... 
2 *IsGetter* (`1 << 1`): specifies that method is a getter ... 
looks better IMO, I do not insist on my proposal, but I dislike 2 pairs of parentheses.

**Comment by Cynerd** [comment]
> > Please use the same formatting as is already used in history (`1` (_name_)).
> 
> Parentheses are used for bit shift already in case of `flags` field, so we will get something like: 2 (_IsGetter_) (`1 << 1`): specifies that method is a getter ...
> 
> 2 `IsGetter` (`1 << 1`): specifies that method is a getter ... 2 _IsGetter_ (`1 << 1`): specifies that method is a getter ... looks better IMO, I do not insist on my proposal, but I dislike 2 pairs of parentheses.

Technically they both say the same thing. It is additional info (alias or representation) for that key.

This PR doesn't put those two parentheses near each other but if you plan to add names for those field as well then I would instead change the `1<<1` formatting instead of not mixing name (that is in italic elsewhere) and definition. How about "[`1 << 1`]"?

**Comment by fvacek** [comment]
> > > Please use the same formatting as is already used in history (`1` (_name_)).
> > 
> > 
> > Parentheses are used for bit shift already in case of `flags` field, so we will get something like: 2 (_IsGetter_) (`1 << 1`): specifies that method is a getter ...
> > 2 `IsGetter` (`1 << 1`): specifies that method is a getter ... 2 _IsGetter_ (`1 << 1`): specifies that method is a getter ... looks better IMO, I do not insist on my proposal, but I dislike 2 pairs of parentheses.
> 
> Technically they both say the same thing. It is additional info (alias or representation) for that key.
> 
> This PR doesn't put those two parentheses near each other but if you plan to add names for those field as well then I would instead change the `1<<1` formatting instead of not mixing name (that is in italic elsewhere) and definition. How about "[`1 << 1`]"?
> 
> Edit: You can also just do "(_IsGetter_, `1 << 1`) 😉

(*IsGetter*, `1 << 1`)  is fine

**Review by Cynerd — APPROVED** [review]
I have now only minor reservation that flags start with upper case while names start with lower case. I would prefer to use camel case throughout but if that is intended to differentiate between flags and keys then I have no issue. I just want to make sure that it was intended.

**Comment by fvacek** [comment]
> I have now only minor reservation that flags start with upper case while names start with lower case. I would prefer to use camel case throughout but if that is intended to differentiate between flags and keys then I have no issue. I just want to make sure that it was intended.

Yes, it is intention. Flags are mapped to enums which start with capital letter, whilst IMap keys are considered to be struct fields which obviously start with small letter.

**Pull request merged**
